<?php
declare(strict_types=1);

namespace jasonwynn10\PFT\forms;

use pocketmine\form\CustomForm;
use pocketmine\form\element\Input;
use pocketmine\form\Form;
use pocketmine\Player;

class SpawnpointForm extends CustomForm {
	/**
	 * SpawnpointForm constructor.
	 */
	public function __construct() {
		$elements   = [];
		$elements[] = new Input("Player username", "Who's spawnpoint are you setting?");
		$elements[] = new Input("X Coordinate", "", "0");
		$elements[] = new Input("Y Coordinate", "", "0");
		$elements[] = new Input("Z Coordinate", "", "0");
		parent::__construct("Spawnpoint Form", $elements);
	}

	/**
	 * @param Player $player
	 *
	 * @return null|Form
	 */
	public function onSubmit(Player $player) : ?Form {
		return parent::onSubmit($player); // TODO: Change the autogenerated stub
	}
}